import os, base64, json, re, uuid
from datetime import datetime
from io import BytesIO
from flask import Blueprint, request, jsonify, send_file, Response, current_app
from flask_jwt_extended import jwt_required, get_jwt_identity
from extensions import db
from models import Engineer, OnsiteReportImage
from sqlalchemy import text
from werkzeug.utils import secure_filename

# ReportLab
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                 TableStyle, HRFlowable, Image, KeepTogether,
                                 PageBreak, BaseDocTemplate, Frame, PageTemplate)
from reportlab.platypus.doctemplate import ActionFlowable
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.pdfgen import canvas as rl_canvas

try:
    from PIL import Image as PILImage
except ImportError:
    PILImage = None

from html.parser import HTMLParser

onsite_bp = Blueprint("onsite", __name__)

FLOTECH_INFO = {
    "name": "PT FLOTECH CONTROLS INDONESIA",
    "address": "Rukan Artha Gading Niaga, Blok F/7",
    "city": "Jl. Boulevard Artha Gading, Jakarta 14240",
    "telp": "Telp: +6221 45850778 / Fax: +6221 45850779",
    "email": "e-Mail: salesjkt@flotech.co.id / Website: www.flotech.com.sg",
}

MAX_DIMENSION = 1280
JPEG_QUALITY  = 80

# ── TRANSLATIONS ──────────────────────────────────────────────────────────────
LABELS = {
    "en": {
        "report_title":       "ONSITE SERVICE REPORT",
        "report_number":      "Report Number",
        "date_of_visit":      "Date of Visit",
        "client_section":     "CLIENT/CUSTOMER INFORMATION",
        "company":            "Company/Agency",
        "client_name":        "Client/PIC Name",
        "contact_person":     "Contact Person",
        "contact_phone":      "Contact Phone",
        "site_location":      "Location/Site",
        "address":            "Address",
        "equipment_section":  "EQUIPMENT/INSTRUMENT DATA",
        "equip_info":         "Equipment/Instrument Information",
        "model_type":         "Model/Type",
        "serial_number":      "Serial Number",
        "engineer":           "Engineer",
        "job_section":        "JOB DETAILS",
        "photo_section":      "DOCUMENTATION & PHOTOS",
        "photo_label":        "Photo",
        "sig_section":        "SIGNATURE",
        "sig_engineer":       "ENGINEER",
        "sig_customer":       "CUSTOMER/CLIENT",
        "reported_by":        "REPORTED BY",
        "digital_notice":     "This document is digitally generated by the system of PT Flotech Controls Indonesia",
        "issued":             "Issued",
        "doc_number":         "Document number",
        "valid_notice":       "This digital document is valid without a wet signature.",
        "generated":          "Generated",
        "page":               "Page",
        "from":               "from",
        "no_serial":          "-",
        "item_no":            "No.",
    },
    "id": {
        "report_title":       "LAPORAN LAYANAN ONSITE",
        "report_number":      "Nomor Laporan",
        "date_of_visit":      "Tanggal Kunjungan",
        "client_section":     "INFORMASI KLIEN/PELANGGAN",
        "company":            "Perusahaan/Instansi",
        "client_name":        "Nama Klien/PIC",
        "contact_person":     "Narahubung",
        "contact_phone":      "Telepon Narahubung",
        "site_location":      "Lokasi/Site",
        "address":            "Alamat",
        "equipment_section":  "DATA PERALATAN/INSTRUMEN",
        "equip_info":         "Informasi Peralatan/Instrumen",
        "model_type":         "Model/Tipe",
        "serial_number":      "Nomor Seri",
        "engineer":           "Teknisi",
        "job_section":        "DETAIL PEKERJAAN",
        "photo_section":      "DOKUMENTASI & FOTO",
        "photo_label":        "Foto",
        "sig_section":        "TANDA TANGAN",
        "sig_engineer":       "TEKNISI",
        "sig_customer":       "PELANGGAN/KLIEN",
        "reported_by":        "DILAPORKAN OLEH",
        "digital_notice":     "Dokumen ini dibuat secara digital oleh sistem PT Flotech Controls Indonesia",
        "issued":             "Diterbitkan",
        "doc_number":         "Nomor dokumen",
        "valid_notice":       "Dokumen digital ini sah tanpa tanda tangan basah.",
        "generated":          "Dibuat",
        "page":               "Halaman",
        "from":               "dari",
        "no_serial":          "-",
        "item_no":            "No.",
    },
}


# ── MODEL ─────────────────────────────────────────────────────────────────────
class OnsiteReport(db.Model):
    __tablename__ = "onsite_reports"

    id              = db.Column(db.Integer, primary_key=True)
    report_number   = db.Column(db.String(50))
    visit_date      = db.Column(db.Date)
    client_name     = db.Column(db.String(150))
    client_company  = db.Column(db.String(200))
    client_address  = db.Column(db.Text)
    site_location   = db.Column(db.String(200))
    contact_person  = db.Column(db.String(150))
    contact_phone   = db.Column(db.String(30))
    engineer_id     = db.Column(db.Integer, db.ForeignKey("engineers.id"), nullable=True)
    job_description = db.Column(db.Text)
    equipment_tag   = db.Column(db.String(100))
    equipment_model = db.Column(db.String(150))
    serial_number   = db.Column(db.String(100))
    work_performed  = db.Column(db.Text)
    findings        = db.Column(db.Text)
    recommendations = db.Column(db.Text)
    materials_used  = db.Column(db.Text)
    equipment_items = db.Column(db.JSON, default=list)
    customer_signature        = db.Column(db.Text)
    status                    = db.Column(db.String(20), default="draft")
    visit_date_from           = db.Column(db.Date)
    visit_date_to             = db.Column(db.Date)
    # NEW: PDF settings
    pdf_language              = db.Column(db.String(5), default="en")
    include_customer_signature = db.Column(db.Boolean, default=True)
    created_by      = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)
    created_at      = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at      = db.Column(db.DateTime, default=datetime.utcnow)

    images = db.relationship("OnsiteReportImage", backref="onsite_report", lazy=True,
                              foreign_keys="OnsiteReportImage.report_id")


def report_to_dict(r, include_sig=False):
    eng = Engineer.query.get(r.engineer_id) if r.engineer_id else None
    images = [
        {
            "id": img.id,
            "file_path": img.file_path,
            "caption": img.caption or "",
            "uploaded_at": img.uploaded_at.isoformat() if img.uploaded_at else None,
        }
        for img in (r.images or [])
    ]
    d = {
        "id": r.id,
        "report_number": r.report_number,
        "visit_date": r.visit_date.isoformat() if r.visit_date else None,
        "visit_date_from": r.visit_date_from.isoformat() if r.visit_date_from else (r.visit_date.isoformat() if r.visit_date else None),
        "visit_date_to": r.visit_date_to.isoformat() if r.visit_date_to else None,
        "client_name": r.client_name,
        "client_company": r.client_company,
        "client_address": r.client_address,
        "site_location": r.site_location,
        "contact_person": r.contact_person,
        "contact_phone": r.contact_phone,
        "engineer_id": r.engineer_id,
        "engineer_name": eng.name if eng else None,
        "engineer_position": eng.position if eng else None,
        "engineer_signature": eng.signature_data if eng else None,
        "job_description": r.job_description,
        "equipment_tag": r.equipment_tag,
        "equipment_model": r.equipment_model,
        "serial_number": r.serial_number,
        "work_performed": r.work_performed,
        "findings": r.findings,
        "recommendations": r.recommendations,
        "materials_used": r.materials_used,
        "equipment_items": r.equipment_items or [],
        "status": r.status,
        "created_at": r.created_at.isoformat() if r.created_at else None,
        "images": images,
        "pdf_language": r.pdf_language or "en",
        "include_customer_signature": r.include_customer_signature if r.include_customer_signature is not None else True,
    }
    if include_sig:
        d["customer_signature"] = r.customer_signature
    return d


@onsite_bp.route('/list', methods=['GET'])
@jwt_required()
def list_reports():
    reports = OnsiteReport.query.order_by(OnsiteReport.created_at.desc()).all()
    return jsonify([report_to_dict(r) for r in reports]), 200


@onsite_bp.route('/create', methods=['POST'])
@jwt_required()
def create_report():
    user_id = int(get_jwt_identity())
    data = request.get_json()

    def parse_date(s):
        try: return datetime.strptime(s, "%Y-%m-%d").date()
        except: return None

    visit_date      = parse_date(data.get("visit_date") or data.get("visit_date_from"))
    visit_date_from = parse_date(data.get("visit_date_from") or data.get("visit_date"))
    visit_date_to   = parse_date(data.get("visit_date_to")) if data.get("visit_date_to") else None

    report_number = data.get("report_number")
    if not report_number:
        now = datetime.utcnow()
        date_str = now.strftime("%Y%m%d")
        prefix = f"OSR-{date_str}-"
        existing = OnsiteReport.query.filter(
            OnsiteReport.report_number.like(f"{prefix}%")
        ).all()
        seqs = []
        for rpt in existing:
            try: seqs.append(int(rpt.report_number.replace(prefix, "")))
            except: pass
        next_seq = max(seqs) + 1 if seqs else 1
        report_number = f"{prefix}{str(next_seq).zfill(3)}"

    # include_customer_signature: default True
    inc_sig = data.get("include_customer_signature")
    if inc_sig is None:
        inc_sig = True

    r = OnsiteReport(
        report_number=report_number,
        visit_date=visit_date,
        visit_date_from=visit_date_from,
        visit_date_to=visit_date_to,
        client_name=data.get("client_name"),
        client_company=data.get("client_company"),
        client_address=data.get("client_address"),
        site_location=data.get("site_location"),
        contact_person=data.get("contact_person"),
        contact_phone=data.get("contact_phone"),
        engineer_id=data.get("engineer_id") or None,
        job_description=data.get("job_description"),
        equipment_tag=data.get("equipment_tag"),
        equipment_model=data.get("equipment_model"),
        serial_number=data.get("serial_number"),
        work_performed=data.get("work_performed"),
        findings=data.get("findings"),
        recommendations=data.get("recommendations"),
        materials_used=data.get("materials_used"),
        equipment_items=data.get("equipment_items") or [],
        customer_signature=data.get("customer_signature"),
        status=data.get("status", "draft"),
        pdf_language=data.get("pdf_language", "en"),
        include_customer_signature=inc_sig,
        created_by=user_id,
    )
    db.session.add(r)
    db.session.commit()
    return jsonify({"message": "Created", "id": r.id}), 201


@onsite_bp.route('/detail/<int:rid>', methods=['GET'])
@jwt_required()
def get_detail(rid):
    r = OnsiteReport.query.get(rid)
    if not r: return jsonify({"error": "Not found"}), 404
    return jsonify(report_to_dict(r, include_sig=True)), 200


@onsite_bp.route('/update/<int:rid>', methods=['PUT'])
@jwt_required()
def update_report(rid):
    r = OnsiteReport.query.get(rid)
    if not r: return jsonify({"error": "Not found"}), 404
    data = request.get_json()
    for field in ["report_number", "client_name", "client_company", "client_address",
                  "site_location", "contact_person", "contact_phone", "job_description",
                  "equipment_tag", "equipment_model", "serial_number", "work_performed",
                  "findings", "recommendations", "materials_used", "customer_signature",
                  "status", "pdf_language"]:
        if field in data:
            setattr(r, field, data[field])
    if "engineer_id" in data:
        r.engineer_id = data["engineer_id"] or None
    if "equipment_items" in data:
        r.equipment_items = data["equipment_items"] or []
    if "include_customer_signature" in data:
        r.include_customer_signature = data["include_customer_signature"]

    def parse_date(s):
        try: return datetime.strptime(s, "%Y-%m-%d").date()
        except: return None

    if data.get("visit_date_from"):
        r.visit_date_from = parse_date(data["visit_date_from"])
        r.visit_date = r.visit_date_from
    elif data.get("visit_date"):
        r.visit_date = parse_date(data["visit_date"])
        r.visit_date_from = r.visit_date

    r.visit_date_to = parse_date(data["visit_date_to"]) if data.get("visit_date_to") else None
    r.updated_at = datetime.utcnow()
    db.session.commit()
    return jsonify({"message": "Updated"}), 200


@onsite_bp.route('/delete/<int:rid>', methods=['DELETE'])
@jwt_required()
def delete_report(rid):
    r = OnsiteReport.query.get(rid)
    if not r: return jsonify({"error": "Not found"}), 404
    for img in (r.images or []):
        try:
            fp = os.path.join(current_app.config["UPLOAD_FOLDER"], img.file_path) \
                 if not os.path.isabs(img.file_path) else img.file_path
            if os.path.exists(fp): os.remove(fp)
        except: pass
        db.session.delete(img)
    db.session.delete(r)
    db.session.commit()
    return jsonify({"message": "Deleted"}), 200


# ── IMAGE UPLOAD ──────────────────────────────────────────────────────────────
@onsite_bp.route('/upload/<int:rid>', methods=['POST'])
@jwt_required()
def upload_images(rid):
    r = OnsiteReport.query.get(rid)
    if not r:
        return jsonify({"error": "Report not found"}), 404

    files = request.files.getlist("images")
    if not files:
        return jsonify({"error": "No files uploaded"}), 400

    saved_files = []

    for file in files:
        if not file.filename:
            continue

        base = secure_filename(file.filename)
        base_no_ext = base.rsplit(".", 1)[0] if "." in base else base
        filename = f"onsite_{base_no_ext}.jpg"

        dest_path = os.path.join(current_app.config["UPLOAD_FOLDER"], filename)
        if os.path.exists(dest_path):
            filename = f"onsite_{base_no_ext}_{uuid.uuid4().hex[:8]}.jpg"
            dest_path = os.path.join(current_app.config["UPLOAD_FOLDER"], filename)

        try:
            img = PILImage.open(file.stream).convert("RGB")
            w, h = img.size
            if w > MAX_DIMENSION or h > MAX_DIMENSION:
                ratio = min(MAX_DIMENSION / w, MAX_DIMENSION / h)
                img = img.resize((int(w * ratio), int(h * ratio)), PILImage.LANCZOS)
            buf = BytesIO()
            img.save(buf, format="JPEG", quality=JPEG_QUALITY, optimize=True)
            buf.seek(0)
            with open(dest_path, "wb") as f_out:
                f_out.write(buf.read())
        except Exception:
            file.stream.seek(0)
            with open(dest_path, "wb") as f_out:
                f_out.write(file.stream.read())

        new_img = OnsiteReportImage(report_id=rid, file_path=filename, caption="")
        db.session.add(new_img)
        saved_files.append(filename)

    db.session.commit()
    return jsonify({"message": "Images uploaded", "files": saved_files}), 201


# ── IMAGE DELETE ──────────────────────────────────────────────────────────────
@onsite_bp.route('/image/delete/<int:image_id>', methods=['DELETE'])
@jwt_required()
def delete_image(image_id):
    img = OnsiteReportImage.query.get(image_id)
    if not img: return jsonify({"error": "Image not found"}), 404
    try:
        fp = os.path.join(current_app.config["UPLOAD_FOLDER"], img.file_path) \
             if not os.path.isabs(img.file_path) else img.file_path
        if os.path.exists(fp): os.remove(fp)
    except: pass
    db.session.delete(img)
    db.session.commit()
    return jsonify({"message": "Image deleted"}), 200


# ── IMAGE CAPTION ─────────────────────────────────────────────────────────────
@onsite_bp.route('/image/caption/<int:image_id>', methods=['PUT'])
@jwt_required()
def update_image_caption(image_id):
    img = OnsiteReportImage.query.get(image_id)
    if not img: return jsonify({"error": "Image not found"}), 404
    data = request.get_json()
    img.caption = data.get("caption", "")
    db.session.commit()
    return jsonify({"message": "Caption updated"}), 200


# ── AUTO-MIGRATE ──────────────────────────────────────────────────────────────
def _ensure_columns():
    try:
        with db.engine.connect() as conn:
            conn.execute(text("""
                ALTER TABLE onsite_reports
                ADD COLUMN IF NOT EXISTS equipment_items JSONB DEFAULT '[]'::jsonb
            """))
            conn.execute(text("""
                ALTER TABLE onsite_reports
                ADD COLUMN IF NOT EXISTS visit_date_from DATE
            """))
            conn.execute(text("""
                ALTER TABLE onsite_reports
                ADD COLUMN IF NOT EXISTS visit_date_to DATE
            """))
            conn.execute(text("""
                ALTER TABLE onsite_reports
                ADD COLUMN IF NOT EXISTS pdf_language VARCHAR(5) DEFAULT 'en'
            """))
            conn.execute(text("""
                ALTER TABLE onsite_reports
                ADD COLUMN IF NOT EXISTS include_customer_signature BOOLEAN DEFAULT TRUE
            """))
            conn.execute(text("""
                UPDATE onsite_reports
                SET visit_date_from = visit_date
                WHERE visit_date_from IS NULL AND visit_date IS NOT NULL
            """))
            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS onsite_report_images (
                    id SERIAL PRIMARY KEY,
                    report_id INTEGER REFERENCES onsite_reports(id) ON DELETE CASCADE,
                    file_path VARCHAR(300),
                    caption VARCHAR(500) DEFAULT '',
                    uploaded_at TIMESTAMP DEFAULT NOW()
                )
            """))
            conn.commit()
    except Exception:
        pass


@onsite_bp.record_once
def _on_register(state):
    with state.app.app_context():
        _ensure_columns()


# ── HTML → ReportLab Paragraphs ───────────────────────────────────────────────
class _HTMLtoParagraphs(HTMLParser):
    def __init__(self, usable_w, text_style, ps_fn, primary, white, accent, border, gray, dark):
        super().__init__()
        self._usable_w = usable_w
        self._ts = text_style
        self._ps = ps_fn
        self._primary = primary
        self._white = white
        self._accent = accent
        self._border = border
        self._gray = gray
        self._dark = dark
        self._paragraphs = []
        self._buf = []
        self._list_type = None
        self._list_counter = 0
        self._img_queue = []
        self._bold = 0
        self._italic = 0
        self._underline = 0
        self._color_stack = []
        self._size_stack = []
        self._align = TA_LEFT

    def _flush_buf(self):
        text = "".join(self._buf).strip()
        self._buf = []
        return text

    def handle_starttag(self, tag, attrs):
        attrmap = dict(attrs)
        style_str = attrmap.get("style", "")
        if tag in ("b", "strong"):
            self._buf.append("<b>"); self._bold += 1
        elif tag in ("i", "em"):
            self._buf.append("<i>"); self._italic += 1
        elif tag in ("u",):
            self._buf.append("<u>"); self._underline += 1
        elif tag == "br":
            self._buf.append("<br/>")
        elif tag in ("p", "div"):
            t = self._flush_buf()
            if t:
                self._paragraphs.append(Paragraph(t, self._ps('HP', fontSize=10, textColor=self._dark, leading=14)))
            align = TA_LEFT
            if "text-align:center" in style_str or "text-align: center" in style_str:
                align = TA_CENTER
            elif "text-align:right" in style_str or "text-align: right" in style_str:
                align = TA_RIGHT
            self._align = align
        elif tag in ("ul",):
            self._list_type = "ul"
        elif tag in ("ol",):
            self._list_type = "ol"; self._list_counter = 0
        elif tag == "li":
            t = self._flush_buf()
            if t:
                self._paragraphs.append(Paragraph(t, self._ps('HP', fontSize=10, textColor=self._dark, leading=14, alignment=self._align)))
            self._list_counter += 1
            if self._list_type == "ol":
                self._buf.append(f"{self._list_counter}. ")
            else:
                self._buf.append("• ")
        elif tag == "font":
            color_val = attrmap.get("color", "")
            if color_val:
                self._buf.append(f'<font color="{color_val}">')
                self._color_stack.append(True)
            size_val = attrmap.get("size", "")
            if size_val:
                self._size_stack.append(True)
        elif tag == "span":
            color_match = re.search(r'color\s*:\s*([^;]+)', style_str)
            size_match = re.search(r'font-size\s*:\s*([^;]+)', style_str)
            if color_match:
                c = color_match.group(1).strip()
                self._buf.append(f'<font color="{c}">')
                self._color_stack.append(True)
            else:
                self._color_stack.append(False)
            if size_match:
                sz_str = size_match.group(1).strip()
                try:
                    px = float(re.sub(r'[^0-9.]', '', sz_str))
                    pt = px * 0.75
                    self._buf.append(f'<font size="{pt:.0f}">')
                    self._size_stack.append(True)
                except:
                    self._size_stack.append(False)
            else:
                self._size_stack.append(False)
        elif tag == "img":
            src = attrmap.get("src", "")
            style_i = attrmap.get("style", "")
            w_cm = 10 * cm
            w_match = re.search(r'width\s*:\s*(\d+(?:\.\d+)?)(px|cm|mm)?', style_i)
            if w_match:
                val = float(w_match.group(1))
                unit = w_match.group(2) or "px"
                if unit == "px": w_cm = min(val * 0.026458 * cm, self._usable_w)
                elif unit == "cm": w_cm = min(val * cm, self._usable_w)
                elif unit == "mm": w_cm = min(val * 0.1 * cm, self._usable_w)
            self._img_queue.append((src, w_cm))

    def handle_endtag(self, tag):
        if tag in ("b", "strong"):
            self._buf.append("</b>"); self._bold -= 1
        elif tag in ("i", "em"):
            self._buf.append("</i>"); self._italic -= 1
        elif tag in ("u",):
            self._buf.append("</u>"); self._underline -= 1
        elif tag in ("p", "div"):
            t = self._flush_buf()
            if t:
                self._paragraphs.append(Paragraph(t, self._ps('HP2', fontSize=10, textColor=self._dark, leading=14, alignment=self._align)))
            self._align = TA_LEFT
        elif tag == "li":
            t = self._flush_buf()
            if t:
                self._paragraphs.append(Paragraph(t, self._ps('LI', fontSize=10, textColor=self._dark, leading=14, leftIndent=12)))
        elif tag in ("ul", "ol"):
            self._list_type = None; self._list_counter = 0
        elif tag == "font":
            if self._color_stack and self._color_stack[-1]:
                self._buf.append("</font>")
            if self._color_stack: self._color_stack.pop()
        elif tag == "span":
            if self._color_stack and self._color_stack[-1]:
                self._buf.append("</font>")
            if self._color_stack: self._color_stack.pop()
            if self._size_stack and self._size_stack[-1]:
                self._buf.append("</font>")
            if self._size_stack: self._size_stack.pop()

    def handle_data(self, data):
        self._buf.append(data)

    def get_elements(self, ps_fn, primary, white, accent, border, dark, usable_w):
        t = self._flush_buf()
        if t:
            self._paragraphs.append(Paragraph(t, ps_fn('HR', fontSize=10, textColor=dark, leading=14)))

        elements = []
        for p in self._paragraphs:
            elements.append(p)
        for src, w_cm in self._img_queue:
            try:
                if src.startswith("data:"):
                    if "base64," in src:
                        b64 = src.split("base64,")[1]
                        decoded = base64.b64decode(b64)
                        buf = BytesIO(decoded)
                        if PILImage:
                            pil = PILImage.open(BytesIO(decoded))
                            ratio = pil.size[1] / pil.size[0]
                            h_cm = w_cm * ratio
                            img = Image(buf, width=w_cm, height=h_cm)
                        else:
                            img = Image(buf, width=w_cm, height=w_cm * 0.6)
                        img.hAlign = 'LEFT'
                        elements.append(Spacer(1, 0.2 * cm))
                        elements.append(img)
                        elements.append(Spacer(1, 0.2 * cm))
            except Exception:
                pass

        return elements


def _html_to_flowables(html_text, usable_w, ps_fn, primary, white, accent, border, gray, dark):
    if not html_text:
        return []
    if not re.search(r'<[a-z]', html_text, re.IGNORECASE):
        return [Paragraph(html_text, ps_fn('PT', fontSize=10, textColor=dark, leading=14))]

    parser = _HTMLtoParagraphs(usable_w, None, ps_fn, primary, white, accent, border, gray, dark)
    try:
        parser.feed(html_text)
    except Exception:
        pass
    return parser.get_elements(ps_fn, primary, white, accent, border, dark, usable_w)


# ── PDF BUILDER ───────────────────────────────────────────────────────────────
def build_onsite_pdf(rid):
    r = OnsiteReport.query.get(rid)
    if not r:
        return None
    eng = Engineer.query.get(r.engineer_id) if r.engineer_id else None
    report_images = OnsiteReportImage.query.filter_by(report_id=rid).order_by(OnsiteReportImage.uploaded_at).all()

    # Language & signature settings
    lang = r.pdf_language or "en"
    if lang not in LABELS:
        lang = "en"
    L = LABELS[lang]
    inc_sig = r.include_customer_signature if r.include_customer_signature is not None else True

    buffer = BytesIO()
    LEFT = RIGHT = 2 * cm
    USABLE_W = 17 * cm

    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            topMargin=2 * cm, bottomMargin=3.5 * cm,
                            leftMargin=LEFT, rightMargin=RIGHT)

    primary   = colors.HexColor("#0B3D91")
    secondary = colors.HexColor("#1E5CC6")
    accent    = colors.HexColor("#EEF3FB")
    dark      = colors.HexColor("#1a1a2e")
    text_clr  = colors.HexColor("#374151")
    gray      = colors.HexColor("#6B7280")
    border    = colors.HexColor("#D1D5DB")
    white     = colors.white

    def ps(name, **kw):
        d = dict(fontName='Helvetica', fontSize=10, textColor=text_clr, leading=14)
        d.update(kw)
        return ParagraphStyle(name, **d)

    elements = []

    # ── HEADER ───────────────────────────────────────────────────
    logo_path = os.path.join(current_app.root_path, "assets", "logo.png")
    logo_col_w = 8 * cm
    title_col_w = USABLE_W - logo_col_w

    if os.path.exists(logo_path):
        try:
            pil_logo = PILImage.open(logo_path)
            lw, lh = pil_logo.size
            target_h = 1.6 * cm
            target_w = min((lw / lh) * target_h, 4.5 * cm)
            logo_cell = Image(logo_path, width=target_w, height=target_h)
        except:
            logo_cell = Paragraph("<b>FLOTECH</b>", ps('LF', fontSize=16, fontName='Helvetica-Bold', textColor=primary))
    else:
        logo_cell = Paragraph("<b>FLOTECH</b>", ps('LF', fontSize=16, fontName='Helvetica-Bold', textColor=primary))

    right_block = Table([
        [Paragraph(L["report_title"], ps('TT', fontSize=14, fontName='Helvetica-Bold', textColor=white, alignment=2))],
        [Paragraph(r.report_number or "", ps('TS', fontSize=9, textColor=colors.HexColor("#BFD3F5"), alignment=2))],
    ], colWidths=[title_col_w])
    right_block.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), primary),
        ('PADDING', (0, 0), (-1, -1), 10),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))

    hdr = Table([[logo_cell, right_block]], colWidths=[logo_col_w, title_col_w])
    hdr.setStyle(TableStyle([('VALIGN', (0, 0), (-1, -1), 'MIDDLE')]))
    elements.append(hdr)
    elements.append(Spacer(1, 0.3 * cm))
    elements.append(HRFlowable(width="100%", thickness=1, color=primary))
    elements.append(Spacer(1, 0.6 * cm))

    # ── META BAND ─────────────────────────────────────────────────
    date_from = r.visit_date_from or r.visit_date
    date_to   = r.visit_date_to
    if date_from and date_to and date_to != date_from:
        if lang == "id":
            MONTHS_ID = ["Januari","Februari","Maret","April","Mei","Juni",
                         "Juli","Agustus","September","Oktober","November","Desember"]
            def fmt_id(d):
                return f"{d.day:02d} {MONTHS_ID[d.month-1]} {d.year}"
            visit_str = f"{fmt_id(date_from)} — {fmt_id(date_to)}"
        else:
            visit_str = f"{date_from.strftime('%d %b %Y')} — {date_to.strftime('%d %b %Y')}"
    elif date_from:
        if lang == "id":
            MONTHS_ID = ["Januari","Februari","Maret","April","Mei","Juni",
                         "Juli","Agustus","September","Oktober","November","Desember"]
            visit_str = f"{date_from.day:02d} {MONTHS_ID[date_from.month-1]} {date_from.year}"
        else:
            visit_str = date_from.strftime("%d %B %Y")
    else:
        visit_str = "-"

    meta_col_w = [3 * cm, 5 * cm, 3 * cm, 6 * cm]
    meta_data = [[
        Paragraph(f"<b>{L['report_number']}</b>", ps('ML', fontSize=8, fontName='Helvetica-Bold', textColor=gray)),
        Paragraph(r.report_number or "-", ps('MV', fontSize=10, fontName='Helvetica-Bold', textColor=dark)),
        Paragraph(f"<b>{L['date_of_visit']}</b>", ps('ML2', fontSize=8, fontName='Helvetica-Bold', textColor=gray)),
        Paragraph(visit_str, ps('MV2', fontSize=9, textColor=dark)),
    ]]
    mt = Table(meta_data, colWidths=meta_col_w)
    mt.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), accent),
        ('BOX', (0, 0), (-1, -1), 0.5, border),
        ('LINEAFTER', (1, 0), (1, 0), 0.5, border),
        ('PADDING', (0, 0), (-1, -1), 9),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    elements.append(mt)
    elements.append(Spacer(1, 0.4 * cm))

    def section(text):
        elements.append(Paragraph(
            f"▌ {text}",
            ps('SH', fontSize=10, fontName='Helvetica-Bold', textColor=primary, spaceBefore=8, spaceAfter=2)
        ))
        elements.append(HRFlowable(width="100%", thickness=0.5, color=border))
        elements.append(Spacer(1, 0.15 * cm))

    # ── CLIENT INFO ───────────────────────────────────────────────
    section(L["client_section"])

    def info_grid(rows):
        table_data = []
        for i in range(0, len(rows), 2):
            left = rows[i]
            right = rows[i + 1] if i + 1 < len(rows) else ("", "")
            table_data.append([
                Paragraph(left[0], ps('IL', fontSize=8, fontName='Helvetica-Bold', textColor=gray)),
                Paragraph(str(left[1] or "—"), ps('IV', fontSize=9, textColor=dark)),
                Paragraph(right[0], ps('IL2', fontSize=8, fontName='Helvetica-Bold', textColor=gray)),
                Paragraph(str(right[1] or "—") if right[1] else "", ps('IV2', fontSize=9, textColor=dark)),
            ])
        t = Table(table_data, colWidths=[3 * cm, 5.5 * cm, 3 * cm, 5.5 * cm])
        t.setStyle(TableStyle([
            ('PADDING', (0, 0), (-1, -1), 7),
            ('LINEBELOW', (0, 0), (-1, -1), 0.2, border),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BACKGROUND', (0, 0), (0, -1), accent),
            ('BACKGROUND', (2, 0), (2, -1), accent),
        ]))
        elements.append(t)

    client_rows = [
        (L["company"],        r.client_company),
        (L["client_name"],    r.client_name),
        (L["contact_person"], r.contact_person),
        (L["contact_phone"],  r.contact_phone),
        (L["site_location"],  r.site_location),
        (L["address"],        r.client_address),
    ]
    client_rows_filtered = [(lbl, v) for lbl, v in client_rows if v]
    if client_rows_filtered:
        info_grid(client_rows_filtered)

    elements.append(Spacer(1, 0.3 * cm))

    # ── EQUIPMENT INFO ────────────────────────────────────────────
    equip_items = r.equipment_items or []
    if not equip_items and any([r.equipment_tag, r.equipment_model, r.serial_number]):
        equip_items = [{
            "description": r.equipment_tag or "",
            "model": r.equipment_model or "",
            "serial_number": r.serial_number or "",
        }]

    if equip_items:
        section(L["equipment_section"])
        for idx, item in enumerate(equip_items):
            desc  = item.get("description", "")
            model = item.get("model", "")
            sn    = item.get("serial_number", "")
            rows = []
            if len(equip_items) > 1:
                rows.append((L["item_no"], str(idx + 1)))
            if desc:
                rows.append((L["equip_info"], desc))
            if model:
                rows.append((L["model_type"], model))
            if sn:
                rows.append((L["serial_number"], sn))
            if idx == 0 and eng:
                rows.append((L["engineer"], eng.name))
            if rows:
                info_grid(rows)
            if idx < len(equip_items) - 1:
                elements.append(Spacer(1, 0.2 * cm))
        elements.append(Spacer(1, 0.3 * cm))
    elif eng:
        section(L["equipment_section"])
        info_grid([(L["engineer"], eng.name), ("", "")])
        elements.append(Spacer(1, 0.3 * cm))

    # ── JOB DETAILS ───────────────────────────────────────────────
    if r.job_description:
        section(L["job_section"])
        job_flowables = _html_to_flowables(
            r.job_description, USABLE_W, ps, primary, white, accent, border, gray, dark
        )
        if job_flowables:
            for fl in job_flowables:
                elements.append(fl)
        elements.append(Spacer(1, 0.4 * cm))

    # ── DOCUMENTATION & PHOTOS ────────────────────────────────────
    if report_images:
        section(L["photo_section"])
        caption_style = ps('Cap', fontSize=8, textColor=gray, alignment=1, leading=11, spaceBefore=3, spaceAfter=6)

        img_table_data = []
        row_imgs = []
        row_caps = []

        for i, img_obj in enumerate(report_images):
            try:
                upload_folder = current_app.config["UPLOAD_FOLDER"]
                img_path = os.path.join(upload_folder, img_obj.file_path) \
                           if not os.path.isabs(img_obj.file_path) else img_obj.file_path
                if not os.path.exists(img_path):
                    img_path = img_obj.file_path

                if os.path.exists(img_path):
                    pil_img = PILImage.open(img_path)
                    w, h = pil_img.size
                    max_w, max_h = 8 * cm, 6 * cm
                    ratio = min(max_w / w, max_h / h)
                    rl_img = Image(img_path, width=w * ratio, height=h * ratio)
                    rl_img.hAlign = 'CENTER'
                    row_imgs.append(rl_img)
                else:
                    row_imgs.append(Paragraph("Image not found", ps('IE', fontSize=8, textColor=gray)))
            except Exception:
                row_imgs.append(Paragraph("Image error", ps('IE2', fontSize=8, textColor=gray)))

            cap_text = img_obj.caption or ""
            row_caps.append(Paragraph(
                f"{L['photo_label']} {i + 1}" + (f": {cap_text}" if cap_text else ""),
                caption_style
            ))

            if len(row_imgs) == 2 or i == len(report_images) - 1:
                while len(row_imgs) < 2:
                    row_imgs.append("")
                    row_caps.append("")
                img_table_data.append(row_imgs)
                img_table_data.append(row_caps)
                row_imgs, row_caps = [], []

        if img_table_data:
            img_t = Table(img_table_data, colWidths=[8.5 * cm, 8.5 * cm])
            img_t.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('PADDING', (0, 0), (-1, -1), 6),
                ('BOX', (0, 0), (0, -1), 0.3, border),
                ('BOX', (1, 0), (1, -1), 0.3, border),
                ('LINEBELOW', (0, 0), (-1, -1), 0.2, border),
            ]))
            elements.append(img_t)
            elements.append(Spacer(1, 0.4 * cm))

    # ── SIGNATURES / REPORTED BY ──────────────────────────────────
    half_w = USABLE_W / 2

    def sig_image(b64_data):
        if not b64_data:
            return Spacer(1, 1.8 * cm)
        try:
            data = b64_data
            if "base64," in data:
                data = data.split("base64,")[1]
            decoded = base64.b64decode(data)
            pil_img = PILImage.open(BytesIO(decoded)).convert("RGBA")
            buf = BytesIO()
            pil_img.save(buf, format="PNG")
            buf.seek(0)
            img = Image(buf, width=4 * cm, height=1.6 * cm)
            img.hAlign = 'CENTER'
            return img
        except:
            return Spacer(1, 1.8 * cm)

    gen_ts = datetime.now().strftime("%d %B %Y, %H:%M WIB")

    digital_notice = Table([[
        Paragraph(
            f'<font color="#6B7280" size="7.5">🔒  {L["digital_notice"]}'
            f'  ·  {L["issued"]}: {gen_ts}'
            f'  ·  {L["doc_number"]}: {r.report_number or "-"}'
            f'  ·  {L["valid_notice"]}</font>',
            ps('DN', fontSize=7.5, textColor=colors.HexColor("#6B7280"), alignment=1, leading=11)
        )
    ]], colWidths=[USABLE_W])
    digital_notice.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F8FAFF")),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#DBEAFE")),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
    ]))

    sig_l   = ps('SL', fontSize=9, fontName='Helvetica-Bold', textColor=primary, alignment=1)
    sig_sub = ps('SS', fontSize=8, textColor=gray, alignment=1, leading=11)

    sig_section_title = Paragraph(
        f"▌ {L['sig_section']}",
        ps('SSH', fontSize=10, fontName='Helvetica-Bold', textColor=primary, spaceBefore=8, spaceAfter=2)
    )
    sig_hr = HRFlowable(width="100%", thickness=0.5, color=border)

    if inc_sig:
        # ── DUAL SIGNATURE LAYOUT ────────────────────────────────
        sig_rows = [
            [Paragraph(L["sig_engineer"], sig_l), Paragraph(L["sig_customer"], sig_l)],
            [sig_image(eng.signature_data if eng else None), sig_image(r.customer_signature)],
            [HRFlowable(width=half_w - 1.5 * cm, thickness=0.5, color=border),
             HRFlowable(width=half_w - 1.5 * cm, thickness=0.5, color=border)],
            [Paragraph(eng.name if eng else "—", sig_sub),
             Paragraph(r.client_name or "—", sig_sub)],
            [Paragraph(
                f"{eng.position or ''}" + (f"  |  {eng.employee_id}" if eng and eng.employee_id else "") if eng else "",
                sig_sub),
             Paragraph(r.client_company or "", sig_sub)],
        ]
        sig_t = Table(sig_rows, colWidths=[half_w, half_w])
        sig_t.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('PADDING', (0, 0), (-1, -1), 8),
            ('BOX', (0, 0), (0, -1), 0.5, border),
            ('BOX', (1, 0), (1, -1), 0.5, border),
            ('BACKGROUND', (0, 0), (0, 0), accent),
            ('BACKGROUND', (1, 0), (1, 0), accent),
        ]))
    else:
        # ── REPORTED BY LAYOUT ───────────────────────────────────
        # Full-width elegant "Reported by" box
        reporter_name = eng.name if eng else "—"
        reporter_pos  = eng.position if eng else ""
        reporter_id   = (f"  |  {eng.employee_id}" if eng and eng.employee_id else "") if eng else ""

        rb_title = Paragraph(L["reported_by"],
            ps('RBT', fontSize=8, fontName='Helvetica-Bold', textColor=primary, alignment=0))
        rb_name  = Paragraph(f"<b>{reporter_name}</b>",
            ps('RBN', fontSize=13, fontName='Helvetica-Bold', textColor=dark, alignment=0, leading=16))
        rb_pos   = Paragraph(f"{reporter_pos}{reporter_id}",
            ps('RBP', fontSize=9, textColor=gray, alignment=0)) if reporter_pos or reporter_id else Spacer(1, 0.1*cm)

        sig_col_w = 5.5 * cm
        text_col_w = USABLE_W - sig_col_w

        sig_cell = sig_image(eng.signature_data if eng else None)

        rb_text_col = Table([
            [rb_title],
            [rb_name],
            [rb_pos],
            [HRFlowable(width=text_col_w - 1*cm, thickness=0.5, color=border)],
        ], colWidths=[text_col_w])
        rb_text_col.setStyle(TableStyle([
            ('PADDING', (0, 0), (-1, -1), 4),
            ('LEFTPADDING', (0, 0), (-1, -1), 12),
            ('TOPPADDING', (0, 0), (0, 0), 12),
            ('BOTTOMPADDING', (0, -1), (0, -1), 12),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))

        sig_t = Table([[rb_text_col, sig_cell]], colWidths=[text_col_w, sig_col_w])
        sig_t.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, 0), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('BOX', (0, 0), (-1, -1), 0.5, border),
            ('LINEAFTER', (0, 0), (0, -1), 0.5, border),
            ('BACKGROUND', (0, 0), (-1, -1), accent),
            ('PADDING', (0, 0), (-1, -1), 10),
        ]))

    sig_block = KeepTogether([
        Spacer(1, 0.4 * cm),
        sig_section_title,
        sig_hr,
        Spacer(1, 0.15 * cm),
        sig_t,
        Spacer(1, 0.3 * cm),
        digital_notice,
    ])
    elements.append(sig_block)

    # ── NUMBERED CANVAS ───────────────────────────────────────────
    class NumberedCanvas(rl_canvas.Canvas):
        def __init__(self, *args, **kwargs):
            rl_canvas.Canvas.__init__(self, *args, **kwargs)
            self._saved_page_states = []

        def showPage(self):
            self._saved_page_states.append(dict(self.__dict__))
            self._startPage()

        def save(self):
            total = len(self._saved_page_states)
            for state in self._saved_page_states:
                self.__dict__.update(state)
                self._draw_footer(self._pageNumber, total)
                rl_canvas.Canvas.showPage(self)
            rl_canvas.Canvas.save(self)

        def _draw_footer(self, page_num, total):
            self.saveState()
            pw, ph = A4
            self.setStrokeColor(primary)
            self.setLineWidth(1)
            self.line(LEFT, 2.8 * cm, pw - RIGHT, 2.8 * cm)
            self.setFont("Helvetica-Bold", 9)
            self.setFillColor(primary)
            self.drawCentredString(pw / 2, 2.3 * cm, FLOTECH_INFO["name"])
            self.setFont("Helvetica", 8)
            self.setFillColor(colors.HexColor("#6B7280"))
            self.drawCentredString(pw / 2, 2.0 * cm, f"{FLOTECH_INFO['address']}  |  {FLOTECH_INFO['city']}")
            self.drawCentredString(pw / 2, 1.7 * cm, FLOTECH_INFO["telp"])
            self.drawCentredString(pw / 2, 1.4 * cm, FLOTECH_INFO["email"])
            self.setFillColor(colors.HexColor("#9CA3AF"))
            self.drawCentredString(pw / 2, 1.0 * cm,
                f"{L['generated']}: {datetime.now().strftime('%d %B %Y %H:%M')}  ·  {L['page']} {page_num} {L['from']} {total}")
            self.restoreState()

    doc.build(elements, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer


@onsite_bp.route('/pdf/<int:rid>', methods=['GET'])
@jwt_required()
def download_pdf(rid):
    r = OnsiteReport.query.get(rid)
    if not r:
        return jsonify({"error": "Not found"}), 404
    buf = build_onsite_pdf(rid)
    if not buf:
        return jsonify({"error": "Failed"}), 500
    return send_file(buf, as_attachment=True,
                     download_name=f"OnsiteReport_{r.report_number}.pdf",
                     mimetype="application/pdf")


@onsite_bp.route('/pdf/preview/<int:rid>', methods=['GET'])
@jwt_required()
def preview_pdf(rid):
    r = OnsiteReport.query.get(rid)
    if not r:
        return jsonify({"error": "Not found"}), 404
    buf = build_onsite_pdf(rid)
    if not buf:
        return jsonify({"error": "Failed"}), 500
    return Response(buf, mimetype="application/pdf",
                    headers={"Content-Disposition": f"inline; filename=OnsiteReport_{r.report_number}.pdf"})